### PR TITLE
Add chart icon

### PR DESCRIPTION
**Pull request by restlessbit**
Adds this lil guy:

screen shot 2017-03-03 at 4 00 41 pm

### CODE REVIEW

**Comment by cmuir** [comment]
What's up with those circles? They look very uncircle-like.

**Comment by restlessbit** [comment]
Say yes

**Comment by restlessbit** [comment]
That's the magic of icon fonts.

**Comment by cmuir** [comment]
Really? It looks pretty bad:

screenshot 2017-03-03 16 02 16

**Comment by restlessbit** [comment]
It's impossible to notice at normal zoom level:

screen shot 2017-03-03 at 4 02 55 pm

**Comment by restlessbit** [comment]
Closing this in favor of #111

**Pull request closed without merging**
