### PR TITLE
Use white background for tooltips

### PR DESCRIPTION
**Pull request by restlessbit**
Updates our tooltips to look like dis:

screen shot 2017-01-26 at 3 45 26 pm

### CODE REVIEW

**Comment by cmuir** [comment]
Does that placement look funky to you? Apologies if that's being handled in a separate PR.

**Comment by restlessbit** [comment]
Maybe. How should the placement be?

**Comment by cmuir** [comment]
Not sure. Trying to find cyber precedents.

**Comment by restlessbit** [comment]
We could do what we are doing now (tooltip underneath item, to the left right or center) http://styleguide.underdog.io/tooltip

**Comment by cmuir** [comment]
With that arrow, too, huh? I kinda miss it.

**Comment by restlessbit** [comment]
I don't.

**Comment by cmuir** [comment]
I guess I might be having trouble seeing the distinction between tooltips and other UI components.

**Comment by cmuir** [comment]
Let's get coffee and discuss. ☕️

**Comment by restlessbit** [comment]
Not a very productive discussion.

**Comment by restlessbit** [comment]
Decreased the size and kept the positioning the same as what we have now:

screen shot 2017-01-26 at 4 31 27 pm

**Comment by restlessbit** [comment]
Oh I decreased the spacing a bit. Not sure if it's not enough spacing.

**Pull request merged**
