### PR TITLE
Add bootcamp icon

### LINKED ISSUE #117: Add boot icon

### PR DESCRIPTION
**Pull request by restlessbit**
Closes #117 

Adds this bugger:

screen shot 2017-03-08 at 3 36 38 pm

### CODE REVIEW

**Comment by brettlangdon** [comment]
@cmuir says no

**Comment by cmuir** [comment]
Oh, I thought it said "boot icon!" This icon is good to go. =)

**Comment by brettlangdon** [comment]
come on @cmuir !

**Comment by brettlangdon** [comment]
don't trust us do ya :p

**Pull request merged**
