### PR TITLE
Add money icon

### PR DESCRIPTION
**Pull request by restlessbit**
$$$

screen shot 2017-01-26 at 1 20 46 pm

### CODE REVIEW

**Comment by cmuir** [comment]
Hmmm, green looks different. Do we have #38BCAC in our palette? Should be. It's the dark green in our logo.

**Comment by restlessbit** [comment]
nah we don't. the dark green in our styleguide is #4CC193. I can update it do match our logo tho.

**Comment by cmuir** [comment]
Cool, let's do that! Not sure where #4CC193 came from. #38BCAC is the sh*t.

**Comment by restlessbit** [comment]
Fo sho. Opened a PR at https://github.com/underdogio/pup/pull/84

**Pull request merged**
