### PR TITLE
Remove auto hyphens from preserve-whitespace helper class

### PR DESCRIPTION
**Pull request by restlessbit**
We decided that we don't want this anymore.

### CODE REVIEW

**Comment by cmuir** [comment]
Are we sure that removing these won't do anything screwy? I recall putting them there for a reason.

**Comment by restlessbit** [comment]
It might cause less than pleasing looking line breaks, which is to be expected.

**Comment by cmuir** [comment]
We might want to visually preview this puppy before we release.

**Comment by cmuir** [comment]
Visual preview = 🎉

**Pull request merged**
